openapi: "3.0.2"
info:
  title: "Training App API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Mock Server"
  - url: "http://localhost:9000"
    description: "Development Server"
paths:
  /:
    get:
      operationId: "healthcheck"
      responses:
        200:
          description: "Healthcheck"
          content:
            plain/text:
              schema:
                type: "string"
                example: "It works"
  /channel:
    get:
      operationId: "getChannels"
      responses:
        200:
          description: "List of channels"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/channel"

components:
  schemas:
    channel:
      type: "object"
      properties:
        id:
          type: "integer"
          example: "1"
        server_id:
          type: "integer"
          example: "1"
        name:
          type: "string"
          example: "General"
