name: Backend Lint

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: read

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Go Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          working-directory: ./backend
  
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    name: Go Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test
        working-directory: ./backend