name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Node Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  test:
    runs-on: ubuntu-latest
    container: node:20.12.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
