name: Lint

on:
  push:
    branches:
      - '*'

jobs:
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          working-directory: ./backend