name: User Service Test
on:
  pull_request:
    paths:
      - 'backend/user/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Kotlin Lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            backend/user

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Lint with Gradle
        working-directory: backend/user
        run: ./gradlew ktlintCheck

  test:
    runs-on: ubuntu-latest
    name: Kotlin Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            backend/user

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        working-directory: backend/user
        run: ./gradlew test
